# Generated by Django 5.0.4 on 2024-04-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='protfolio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
