# Generated by Django 5.0.4 on 2024-04-27 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_image_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='image',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='team',
            name='desc',
            field=models.TextField(blank=True, default='No Description', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='media/project_load.jpg', null=True, upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='expert',
            field=models.CharField(default='No Expert', max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(default='media/team_load.jpg', upload_to='team_images/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='No Name', max_length=100),
        ),
        migrations.CreateModel(
            name='ProService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('rating', models.FloatField()),
                ('process', models.TextField()),
                ('you_get', models.TextField()),
                ('deliveryTime', models.IntegerField()),
                ('revision', models.IntegerField()),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.team')),
                ('images', models.ManyToManyField(to='app.image')),
            ],
        ),
        migrations.CreateModel(
            name='ProServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_title', models.CharField(max_length=100)),
                ('basic_desc', models.TextField()),
                ('basic_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('basic_delivery_time', models.IntegerField()),
                ('basic_revision', models.IntegerField()),
                ('standard_title', models.CharField(max_length=100)),
                ('standard_desc', models.TextField()),
                ('standard_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('standard_delivery_time', models.IntegerField()),
                ('standard_revision', models.IntegerField()),
                ('premium_title', models.CharField(max_length=100)),
                ('premium_desc', models.TextField()),
                ('premium_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('premium_delivery_time', models.IntegerField()),
                ('premium_revision', models.IntegerField()),
                ('proService', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.proservice')),
            ],
        ),
    ]
