# Generated by Django 5.0.4 on 2024-04-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_image_created_date_image_image_image_updated_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
