# Generated by Django 5.0.4 on 2024-04-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_proservice_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proservice',
            name='images',
        ),
        migrations.AddField(
            model_name='proservice',
            name='images1',
            field=models.ImageField(blank=True, default='media/project_load.jpg', null=True, upload_to='proservice_images/'),
        ),
        migrations.AddField(
            model_name='proservice',
            name='images2',
            field=models.ImageField(blank=True, default='media/project_load.jpg', null=True, upload_to='proservice_images/'),
        ),
        migrations.AddField(
            model_name='proservice',
            name='images3',
            field=models.ImageField(blank=True, default='media/project_load.jpg', null=True, upload_to='proservice_images/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
