# Generated by Django 5.0.4 on 2024-04-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_proservice_id_alter_proservicepackage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proservice',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
